{
    "name": "Stock Location History",
    "version": "18.0.2.0.0",
    "license": "AGPL-3",
    "website": "https://github.com/OCA/stock-logistics-warehouse",
    "author": "Open Source Integrators, Odoo Community Association (OCA)",
    "depends": ["stock", "gaqsa_plc"],
    "category": "Stock",
    "summary": "Silo management with stages, macrolots, quality data and PLC integration",
    "data": [
        "security/ir.model.access.csv",
        "data/stock_location_stage_data.xml",
        "views/stock_location_views.xml",
        "views/stock_location_stage_views.xml",
        "views/stock_location_history_views.xml",
        "views/stock_lot_views.xml",
        "wizard/stock_inventory_report_wizard_views.xml",
        "report/stock_inventory_report.xml",
    ],
    "development_status": "Beta",
    "maintainers": ["jasiel-OSI"],
}
